//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.26 at 02:53:23 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8010/soap_api_with_springboot", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package localhost._8010.soap_api_with_springboot;
